# Generated by Django 3.1.7 on 2021-03-30 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=256)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenChangePassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=256)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_login', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('permission', models.IntegerField(choices=[(100, 'regular'), (200, 'manager'), (300, 'inspector'), (400, 'super_manager'), (500, 'ceo')], default=100)),
                ('count_login_now', models.PositiveIntegerField(default=0)),
                ('last_login_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('registration_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('mailboxes', models.ManyToManyField(related_name='mailboxes', to='forum.Mailbox')),
                ('messages', models.ManyToManyField(related_name='my_messages', to='forum.Message')),
                ('posts', models.ManyToManyField(related_name='my_posts', to='forum.Post')),
                ('system_messages', models.ManyToManyField(related_name='system_messages', to='forum.SystemMessage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
