# Generated by Django 3.1.7 on 2021-03-30 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('data', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('permission', models.IntegerField(choices=[(100, 'regular'), (200, 'manager'), (300, 'inspector'), (400, 'super_manager'), (500, 'ceo')], default=0)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_quoted', models.BooleanField(default=False)),
                ('last_change_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('id_message', models.CharField(default='', max_length=256)),
                ('post_id', models.CharField(default='', max_length=256)),
                ('history', models.ManyToManyField(related_name='history_message', to='forum.HistoryMessage')),
                ('last_change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_change_user', to=settings.AUTH_USER_MODEL)),
                ('quoteds', models.ManyToManyField(related_name='quoted_messages', to='forum.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('permission', models.IntegerField(choices=[(100, 'regular'), (200, 'manager'), (300, 'inspector'), (400, 'super_manager'), (500, 'ceo')], default=300)),
                ('last_change_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('data', models.TextField()),
                ('history', models.ManyToManyField(related_name='history_system_message', to='forum.HistoryMessage')),
                ('last_change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_change_user_message', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('data', models.TextField()),
                ('private_message_id', models.CharField(default='', max_length=256)),
                ('permission', models.IntegerField(choices=[(100, 'regular'), (200, 'manager'), (300, 'inspector'), (400, 'super_manager'), (500, 'ceo')], default=100)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressee', to=settings.AUTH_USER_MODEL)),
                ('user_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_send', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox_id', models.CharField(default='', max_length=256)),
                ('last_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_private_message', to='forum.privatemessage')),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_user', to=settings.AUTH_USER_MODEL)),
                ('private_message', models.ManyToManyField(related_name='private_message', to='forum.PrivateMessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_send_private_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_forum', models.CharField(default='', max_length=256)),
                ('category_id', models.CharField(default='', max_length=256)),
                ('permission', models.IntegerField(choices=[(100, 'regular'), (200, 'manager'), (300, 'inspector'), (400, 'super_manager'), (500, 'ceo')], default=0)),
                ('name', models.TextField()),
                ('inspector', models.ManyToManyField(related_name='inspectors', to=settings.AUTH_USER_MODEL)),
                ('mangers', models.ManyToManyField(related_name='mangers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.CharField(default='', max_length=256)),
                ('permission', models.IntegerField(choices=[(100, 'regular'), (200, 'manager'), (300, 'inspector'), (400, 'super_manager'), (500, 'ceo')], default=0)),
                ('name', models.TextField()),
                ('forums', models.ManyToManyField(related_name='forums_category', to='forum.Forum')),
                ('inspector', models.ManyToManyField(related_name='inspectors_category', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forum.message')),
                ('id_post', models.CharField(default='', max_length=256)),
                ('title', models.TextField()),
                ('forum_id', models.CharField(default='', max_length=256)),
                ('views', models.IntegerField(default=0)),
                ('messages', models.ManyToManyField(related_name='messages', to='forum.Message')),
            ],
            bases=('forum.message',),
        ),
        migrations.AddField(
            model_name='forum',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='forum.Post'),
        ),
    ]
